name: Just3DThings
favicon: null
layout_spectrum: 0.39186951890587807
typography_spectrum: 0.5356734492816031
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.22061057132668793
  lightness: 0.10579574154689908
  saturation: 0.14728961931541562
  rhythmicContrast: 0.23732725530862808
purpose: []
